# API Guidelines Ruleset
# This ruleset enforces the API design standards described in our API Guidelines document.
# Structure follows the same organization as the main guidelines document for easy reference.

# OpenAPI Specification version 3.x
extends: [spectral:oas]
functionsDir: ./functions
functions:
  - allowEtClientNameHeader

rules:
  # =============================================================================
  # 1. Introduction - Not lintable
  # =============================================================================

  # =============================================================================
  # 2. Core Principles
  # =============================================================================

  # -------------------------------------------------------------------------
  # 2.1 General Design Principles
  # -------------------------------------------------------------------------

  entur-info-title:
    message: "The OpenAPI info section MUST include a non-empty \"title\"."
    severity: error
    given: $
    then:
      field: info.title
      function: truthy

  entur-info-title-no-api:
    message: "API titles SHOULD NOT contain the word 'api'."
    severity: warn
    given: $.info.title
    then:
      function: pattern
      functionOptions:
        notMatch: "/\\bapi\\b/i"

  info-description: error

  # HTTP Methods
  entur-operation-standard-methods:
    message: "Operations SHOULD use standard HTTP methods (`get`, `post`, `put`, `patch`, `delete`). Invalid operation: {{property}}."
    given: $.paths[*]
    severity: warn
    then:
      field: "@key"
      function: pattern
      functionOptions:
        notMatch: "^(options|head|trace)$"

  # Documentation with examples
  entur-example-parameter:
    message: "Parameters SHOULD have example values."
    severity: warn
    recommended: false
    given: $.paths.*.*.parameters.*
    then:
      field: example
      function: defined

  entur-parameter-description:
    message: "Parameters SHOULD have a description."
    severity: warn
    given: $.paths.*.*.parameters.*
    then:
      field: description
      function: truthy

  entur-example-schema-property:
    message: "Properties in components schema SHOULD have example values."
    severity: warn
    recommended: false
    given: $.components.schemas.*.properties.*
    then:
      field: example
      function: defined

  entur-request-body-examples:
    message: "Request bodies SHOULD include at least one example."
    severity: warn
    given: $.paths.*.*.requestBody.content.*
    then:
      function: schema
      functionOptions:
        schema:
          anyOf:
            - required: ["example"]
            - required: ["examples"]
            - allOf:
                - required: ["schema"]
                - properties:
                    schema:
                      anyOf:
                        - required: ["example"]
                        - required: ["examples"]

  entur-request-body-description:
    message: "Request bodies SHOULD have a description."
    severity: warn
    given: $.paths.*.*.requestBody
    then:
      field: description
      function: truthy

  entur-response-body-examples:
    message: "Response bodies SHOULD include at least one example."
    severity: warn
    given: $.paths.*.*.responses.*.content.*
    then:
      function: schema
      functionOptions:
        schema:
          anyOf:
            - required: ["example"]
            - required: ["examples"]
            - allOf:
                - required: ["schema"]
                - properties:
                    schema:
                      anyOf:
                        - required: ["example"]
                        - required: ["examples"]


  entur-operation-summary:
    message: "Operations SHOULD have a non-empty summary field."
    severity: warn
    given: $.paths.*[get,post,put,patch,delete,options,head,trace]
    then:
      field: summary
      function: truthy

  # openapi spec version 3
  entur-openapi-version-3:
    message: "OpenAPI specification must use version 3.x"
    severity: error
    given: "$"
    then:
      - field: openapi
        function: pattern
        functionOptions:
          match: "^3\\.\\d+\\.\\d+$"
      - field: swagger
        function: falsy

  # Security - HTTPS requirement
  entur-hosts-https-only:
    message: "Servers MUST use HTTPS. Invalid URL: {{value}}"
    severity: error
    given: $.servers[*].url
    then:
      function: pattern
      functionOptions:
        match: ^(https:)

  entur-hosts-not-localhost:
    message: "Server URLs SHOULD NOT use localhost or 127.0.0.1 as hostname. Invalid URL: {{value}}"
    severity: warn
    given: $.servers[*].url
    then:
      function: pattern
      functionOptions:
        notMatch: "https?://(localhost|127\\.0\\.0\\.1)(/|$)"
      invert: true
  
  # -------------------------------------------------------------------------
  # 2.3 Authentication and authorization
  # -------------------------------------------------------------------------

  entur-permissions:
    message: "x-entur-permissions must match the schema"
    severity: error
    given: $.paths.*[get,post,put,patch,delete,options,head,trace].x-entur-permissions
    then:
      function: schema
      functionOptions:
        schema:
          type: object
          required:
            - value
          properties:
            description:
              type: string
            value:
              $ref: "#/$defs/permission-node"
          $defs:
            permission-node:
              oneOf:
                - $ref: "#/$defs/permission-leaf"
                - $ref: "#/$defs/permission-all"
                - $ref: "#/$defs/permission-any"

            permission-leaf:
              type: string
              pattern: "^[0-9a-zA-ZæøåØÆÅ][0-9a-zA-ZæøåØÆÅ.\\-]{0,99}:(les|opprett|endre|slett)$"

            permission-all:
              type: object
              required:
                - all
              properties:
                all:
                  type: array
                  items:
                    - $ref: "#/$defs/permission-node"

            permission-any:
              type: object
              required:
                - any
              properties:
                any:
                  type: array
                  items:
                    - $ref: "#/$defs/permission-node"



  # =============================================================================
  # 3. Naming & Structure Conventions
  # =============================================================================

  # -------------------------------------------------------------------------
  # 3.1 Resource Naming
  # -------------------------------------------------------------------------

  # URL format requirements
  entur-paths-format:
    message: "Paths MUST be in kebab-case (lower case and separated with hyphens), with single slashes, and no trailing slash at end of path. Invalid path: {{property}}."
    severity: error
    given: $.paths.*~
    then:
      function: pattern
      functionOptions:
        #Match leading slash followed by kebab casing, and then optional trailing kebab with url params allowed. No trailing slash.
        #Double slashes now allowed.
        #Custom functions not allowed in path for now (e.g. /ecards/{mediaSerialNumberId}:block)
        match: ^(\/[a-z0-9]+(-[a-z0-9]+)*)(\/[a-z0-9]+(-[a-z0-9]+)*|\/{.+})*$

  # Field naming conventions
  entur-query-parameters-lower-camel-case:
    message: "Query parameter names MUST be lowerCamelCase. Invalid name: {{value}}"
    severity: error
    given: $.paths.*.*.parameters[?(@.in=='query')].name
    then:
      function: pattern
      functionOptions:
        match: ^[a-z][a-zA-Z0-9]*$

  entur-path-parameters-camelCase-alphanumeric:
    message: "Path parameter names MUST be lowerCamelCase. Invalid name: {{value}}"
    severity: error
    given: $..parameters[?(@.in == 'path')].name
    then:
      function: pattern
      functionOptions:
        match: ^[a-z][a-zA-Z0-9]*$

  entur-body-fields-lower-camel-case:
    message: "Request and Response body field names MUST be lowerCamelCase."
    severity: error
    given: $..[?(@property === 'properties')]
    then:
      field: "@key"
      function: pattern
      functionOptions:
        match: ^[a-z][a-zA-Z0-9]*$

# Server URL case requirements
  entur-server-urls-lowercase:
    message: "Server URLs MUST be in lowercase. Invalid URL: {{value}}"
    severity: error
    given: $.servers[*].url
    then:
      function: pattern
      functionOptions:
        match: ^[^A-Z]*$

  # Avoid 'api' in paths
  entur-paths-with-api:
    message: "Paths SHOULD NOT contain 'api'."
    severity: warn
    given: $.paths.*~
    then:
      function: pattern
      functionOptions:
        notMatch: "^(?!\/api-docs$).*\\bapi\\b.*$"

  # -------------------------------------------------------------------------
  # 3.2 Versioning
  # -------------------------------------------------------------------------

  entur-info-version:
    message: "The OpenAPI info.version MUST be a valid semantic version (MAJOR.MINOR.PATCH format, e.g. 1.0.0)."
    severity: error
    given: $
    then:
      field: info.version
      function: pattern
      functionOptions:
        match: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$"

  # -------------------------------------------------------------------------
  # 3.3 Backward Compatibility - Not directly lintable
  # -------------------------------------------------------------------------


  # =============================================================================
  # 4. Communication Standards
  # =============================================================================


  # -------------------------------------------------------------------------
  # 4.1 HTTP Status Codes
  # -------------------------------------------------------------------------

  # Request body allowed methods
  entur-request-body-allowed-methods:
    message: "Request body is allowed only for PUT, POST, and PATCH."
    severity: error
    given:
      - "$.paths[*].get.requestBody"
      - "$.paths[*].delete.requestBody"
      - "$.paths[*].options.requestBody"
      - "$.paths[*].head.requestBody"
      - "$.paths[*].trace.requestBody"
    then:
      function: falsy

  # HTTP method responses validation
  entur-get-responses-validation:
    message: "Invalid response code: {{property}}. GET responses MUST use one of these response codes: 200, 304, 400, 401, 403, 404, 500, 503"
    severity: error
    given: $.paths.*.get.responses.*~
    then:
      function: enumeration
      functionOptions:
        values: ["200", "304", "400", "401", "403", "404", "500", "503"]

  entur-delete-responses-validation:
    message: "Invalid response code: {{property}}. DELETE responses MUST use one of these response codes: 200, 204, 400, 401, 403, 404, 409, 500, 503"
    severity: error
    given: $.paths.*.delete.responses.*~
    then:
      function: enumeration
      functionOptions:
        values: ["200", "204", "400", "401", "403", "404", "409", "500", "503"]

  entur-post-responses-validation:
    message: "Invalid response code: {{property}}. POST responses MUST use one of these response codes: 200, 201, 202, 204, 303, 400, 401, 403, 404, 409, 500, 503"
    severity: error
    given: $.paths.*.post.responses.*~
    then:
      function: enumeration
      functionOptions:
        values: ["200", "201", "202", "204", "303", "400", "401", "403", "404", "409", "500", "503"]

  entur-put-responses-validation:
    message: "Invalid response code: {{property}}. PUT responses MUST use one of these response codes: 200, 204, 400, 401, 403, 404, 409, 500, 503"
    severity: error
    given: $.paths.*.put.responses.*~
    then:
      function: enumeration
      functionOptions:
        values: ["200", "204", "400", "401", "403", "404", "409", "500", "503"]

  entur-patch-responses-validation:
    message: "Invalid response code: {{property}}. PATCH responses MUST use one of these response codes: 200, 204, 400, 401, 403, 404, 409, 500, 503"
    severity: error
    given: $.paths.*.patch.responses.*~
    then:
      function: enumeration
      functionOptions:
        values: ["200", "204", "400", "401", "403", "404", "409", "500", "503"]


  # -------------------------------------------------------------------------
  # 4.2 Error Handling - RFC 9457 compliance
  # -------------------------------------------------------------------------

  # Error response format validation
  entur-rfc-9457-content-type:
    message: "Error responses MUST have content type application/problem+json or application/problem+xml"
    severity: error
    given: $.paths.*.*.responses[?(@property.match(/^(4|5)/))]
    then:
      - field: content
        function: truthy
      - field: content
        function: schema
        functionOptions:
          # JSON Schema to require either the JSON or XML problem media-type
          schema:
            type: object
            anyOf:
              - required: ["application/problem+json"]
              - required: ["application/problem+xml"]

  entur-rfc-9457-body-title:
    message: "Error responses MUST have property 'title'."
    severity: error
    given: $.paths.*.*.responses[?(@property.match(/^(4|5)/))].content.*.schema.properties
    then:
      field: title
      function: defined

  entur-rfc-9457-body-status:
    message: "Error responses MUST have property 'status'."
    severity: error
    given: $.paths.*.*.responses[?(@property.match(/^(4|5)/))].content.*.schema.properties
    then:
      field: status
      function: defined

  entur-rfc-9457-body-detail:
    message: "Error responses SHOULD have property 'detail' to provide additional context."
    severity: warn
    given: $.paths.*.*.responses[?(@property.match(/^(4|5)/))].content.*.schema.properties
    then:
      field: detail
      function: defined


  # =============================================================================
  # 5. Data Formatting Standards
  # =============================================================================


  # -------------------------------------------------------------------------
  # 5.1 Language & Spelling
  # -------------------------------------------------------------------------

  entur-language-headers:
    message: "Accept-Language and Content-Language should follow IETF BCP 47. And macrolanguages like 'no' should not be used - use 'nb' or 'nn'."
    severity: error
    given:
      - $..parameters[?(@.in=='header' && @.name=='Accept-Language')].example
      - $..parameters[?(@.in=='header' && @.name=='Accept-Language')].schema.example
      - $..parameters[?(@.in=='header' && @.name=='Accept-Language')].schema.default
      - $..parameters[?(@.in=='header' && @.name=='Content-Language')].example
      - $..parameters[?(@.in=='header' && @.name=='Content-Language')].schema.example
      - $..parameters[?(@.in=='header' && @.name=='Content-Language')].schema.default
    then:
      function: pattern
      functionOptions:
        notMatch: "^(nob|nno|eng|nor|no)\\b"

  # -------------------------------------------------------------------------
  # 5.2 Date & Time - Requires runtime validation
  # -------------------------------------------------------------------------


  # -------------------------------------------------------------------------
  # 5.3 Currency Representation - Requires runtime validation
  # -------------------------------------------------------------------------


  # -------------------------------------------------------------------------
  # 5.4 Character Encoding - Not directly lintable for UTF-8
  # -------------------------------------------------------------------------


  # -------------------------------------------------------------------------
  # 5.5 HTTP Headers
  # -------------------------------------------------------------------------

  # Required ET-Client-Name header

  entur-require-et-client-name-header:
    message: "All operations SHOULD allow header \"ET-Client-Name\" (at path or operation level)."
    severity: warn
    given: $.paths[*]
    then:
      function: allowEtClientNameHeader

  # Header naming conventions
  entur-headers-hyphenated-pascal-case:
    message: "HTTP header names MUST be in Hyphenated-Pascal-Case. Invalid name: \"{{value}}\"."
    severity: error
    given: "$..parameters[?(@.in == 'header' && @.name != 'ET-Client-Name')].name"
    then:
      function: pattern
      functionOptions:
        match: ^([A-Z][a-z0-9]*)(-[A-Z][a-z0-9]*)*$


  # =============================================================================
  # 6. Advanced Design Patterns
  # =============================================================================

  # Most advanced design patterns require runtime validation or manual review
  # The rules here focus on aspects that can be statically verified


  # -------------------------------------------------------------------------
  # 6.5 Import & Export Formats - Accept header validation handled at runtime
  # -------------------------------------------------------------------------


  # -------------------------------------------------------------------------
  # 6.6 Validation - Error response format covered in section 4.2
  # -------------------------------------------------------------------------


  # -------------------------------------------------------------------------
  # 6.7 HATEOAS - Not directly lintable, requires manual review
  # -------------------------------------------------------------------------
